// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE10E8-1513-4C36-BDAA-041E3E34DEF7

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

static const R_CallMethodDef CallEntries[] = {
    {NULL, NULL, 0}
};

RcppExport void R_init_AirRoute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
