// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_haversine_km
double dist_haversine_km(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _AirRoute_dist_haversine_km(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(dist_haversine_km(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// route_length_km
double route_length_km(NumericVector lats, NumericVector lons);
RcppExport SEXP _AirRoute_route_length_km(SEXP latsSEXP, SEXP lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(route_length_km(lats, lons));
    return rcpp_result_gen;
END_RCPP
}
// route_cumulative_length_km
NumericVector route_cumulative_length_km(NumericVector lats, NumericVector lons);
RcppExport SEXP _AirRoute_route_cumulative_length_km(SEXP latsSEXP, SEXP lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lons(lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(route_cumulative_length_km(lats, lons));
    return rcpp_result_gen;
END_RCPP
}
// initial_bearing_deg
double initial_bearing_deg(double lat1, double lon1, double lat2, double lon2);
RcppExport SEXP _AirRoute_initial_bearing_deg(SEXP lat1SEXP, SEXP lon1SEXP, SEXP lat2SEXP, SEXP lon2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    rcpp_result_gen = Rcpp::wrap(initial_bearing_deg(lat1, lon1, lat2, lon2));
    return rcpp_result_gen;
END_RCPP
}
// destination_point
NumericVector destination_point(double lat, double lon, double bearing_deg, double distance_km);
RcppExport SEXP _AirRoute_destination_point(SEXP latSEXP, SEXP lonSEXP, SEXP bearing_degSEXP, SEXP distance_kmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< double >::type bearing_deg(bearing_degSEXP);
    Rcpp::traits::input_parameter< double >::type distance_km(distance_kmSEXP);
    rcpp_result_gen = Rcpp::wrap(destination_point(lat, lon, bearing_deg, distance_km));
    return rcpp_result_gen;
END_RCPP
}
// cross_track_segment_km
double cross_track_segment_km(double lat_p, double lon_p, double lat_a, double lon_a, double lat_b, double lon_b);
RcppExport SEXP _AirRoute_cross_track_segment_km(SEXP lat_pSEXP, SEXP lon_pSEXP, SEXP lat_aSEXP, SEXP lon_aSEXP, SEXP lat_bSEXP, SEXP lon_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat_p(lat_pSEXP);
    Rcpp::traits::input_parameter< double >::type lon_p(lon_pSEXP);
    Rcpp::traits::input_parameter< double >::type lat_a(lat_aSEXP);
    Rcpp::traits::input_parameter< double >::type lon_a(lon_aSEXP);
    Rcpp::traits::input_parameter< double >::type lat_b(lat_bSEXP);
    Rcpp::traits::input_parameter< double >::type lon_b(lon_bSEXP);
    rcpp_result_gen = Rcpp::wrap(cross_track_segment_km(lat_p, lon_p, lat_a, lon_a, lat_b, lon_b));
    return rcpp_result_gen;
END_RCPP
}
// cross_track_route_km
double cross_track_route_km(double lat_p, double lon_p, NumericVector plan_lats, NumericVector plan_lons);
RcppExport SEXP _AirRoute_cross_track_route_km(SEXP lat_pSEXP, SEXP lon_pSEXP, SEXP plan_latsSEXP, SEXP plan_lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat_p(lat_pSEXP);
    Rcpp::traits::input_parameter< double >::type lon_p(lon_pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plan_lats(plan_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plan_lons(plan_lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(cross_track_route_km(lat_p, lon_p, plan_lats, plan_lons));
    return rcpp_result_gen;
END_RCPP
}
// track_cross_track_km
NumericVector track_cross_track_km(NumericVector track_lats, NumericVector track_lons, NumericVector plan_lats, NumericVector plan_lons);
RcppExport SEXP _AirRoute_track_cross_track_km(SEXP track_latsSEXP, SEXP track_lonsSEXP, SEXP plan_latsSEXP, SEXP plan_lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type track_lats(track_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type track_lons(track_lonsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plan_lats(plan_latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plan_lons(plan_lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(track_cross_track_km(track_lats, track_lons, plan_lats, plan_lons));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AirRoute_dist_haversine_km", (DL_FUNC) &_AirRoute_dist_haversine_km, 4},
    {"_AirRoute_route_length_km", (DL_FUNC) &_AirRoute_route_length_km, 2},
    {"_AirRoute_route_cumulative_length_km", (DL_FUNC) &_AirRoute_route_cumulative_length_km, 2},
    {"_AirRoute_initial_bearing_deg", (DL_FUNC) &_AirRoute_initial_bearing_deg, 4},
    {"_AirRoute_destination_point", (DL_FUNC) &_AirRoute_destination_point, 4},
    {"_AirRoute_cross_track_segment_km", (DL_FUNC) &_AirRoute_cross_track_segment_km, 6},
    {"_AirRoute_cross_track_route_km", (DL_FUNC) &_AirRoute_cross_track_route_km, 4},
    {"_AirRoute_track_cross_track_km", (DL_FUNC) &_AirRoute_track_cross_track_km, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AirRoute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
