# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title 
#' distance (Haversine)
#'
#' @description
#' computes the distance between two points on the WGS84 sphere
#' using the haversine formula (with Earth radius 6371.0088 km).
#'
#' @param lat1 latitude of point 1 (degs).
#' @param lon1 longitude of point 1 (degs).
#' @param lat2 latitude of point 2 (degs).
#' @param lon2 longitude of point 2 (degs).
#'
#' @return 
#' distance in km.
#'
#' @examples
#' dist_haversine_km(52.1657, 20.9671, 51.47, -0.4543)  # waw -> lhr ~ 1460-70km
#'
#' @encoding UTF-8
#' @export
dist_haversine_km <- function(lat1, lon1, lat2, lon2) {
    .Call(`_AirRoute_dist_haversine_km`, lat1, lon1, lat2, lon2)
}

#' @title 
#' route length along waypoints
#'
#' @description
#' sums haversine leg distances between consecutive waypoints
#' \code{(lat[i-1], lon[i-1])} to \code{(lat[i], lon[i])}.
#'
#' @param lats numeric vector of latitudes (degs).
#' @param lons numeric vector of longitudes (degs), same length as \code{lats}.
#'
#' @return 
#' total route length in km (0 if fewer than 2 points couse it makes no sense then).
#'
#' @encoding UTF-8
#' @export
route_length_km <- function(lats, lons) {
    .Call(`_AirRoute_route_length_km`, lats, lons)
}

#' @title 
#' cumulative route length in array
#'
#' @description
#' returns cumulative haversine distance along a sequence of waypoints.
#' the first element is 0; the last equals \code{\link{route_length_km}(lats, lons)}.
#'
#' @param lats numeric vector of latitudes (degs).
#' @param lons numeric vector of longitudes (degs).
#'
#' @return numeric vector of cumulative distances in km.
#'
#' @encoding UTF-8
#' @export
route_cumulative_length_km <- function(lats, lons) {
    .Call(`_AirRoute_route_cumulative_length_km`, lats, lons)
}

#' @title 
#' initial bearing (deg)
#'
#' @description
#' computes the initial bearing (deg) between two points on the WGS84 sphere.
#'
#' @param lat1 latitude of point 1 (degs).
#' @param lon1 longitude of point 1 (degs).
#' @param lat2 latitude of point 2 (degs).
#' @param lon2 longitude of point 2 (degs).
#'
#' @return initial bearing in degrees, clockwise from north (0--360).
#'
#' @examples
#' initial_bearing_deg(52.1657, 20.9671, 50.0379, 8.5622)  # WAW -> FRA ~ 260 deg
#'
#' @encoding UTF-8
#' @export
initial_bearing_deg <- function(lat1, lon1, lat2, lon2) {
    .Call(`_AirRoute_initial_bearing_deg`, lat1, lon1, lat2, lon2)
}

#' @title
#' destination point along a haversine arc
#'
#' @description
#' given a start point, initial bearing, and distance, returns the
#' destination on the WGS84 sphere (haversine forward geodesic).
#'
#' @param lat latitude of start point (degs).
#' @param lon longitude of start point (degs).
#' @param bearing_deg initial bearing (degs, clockwise from north).
#' @param distance_km distance to travel (km).
#'
#' @return numeric vector of length 2: latitude and longitude (degs).
#'
#' @examples
#' destination_point(52.1657, 20.9671, 90, 100)
#'
#' @encoding UTF-8
#' @export
destination_point <- function(lat, lon, bearing_deg, distance_km) {
    .Call(`_AirRoute_destination_point`, lat, lon, bearing_deg, distance_km)
}

